const colors = {
  light: {
    text: '#0A0A1A',
    tint: '#7B5FFA',
    background: '#F2F2FF',
    foreground: '#0A0A1A',
    card: '#FFFFFF',
    cardForeground: '#0A0A1A',
    primary: '#7B5FFA',
    primaryForeground: '#FFFFFF',
    secondary: '#EEEEFF',
    secondaryForeground: '#2A2A5A',
    muted: '#EEEEFF',
    mutedForeground: '#6A6A9A',
    accent: '#00B4E6',
    accentForeground: '#FFFFFF',
    destructive: '#FF3B5C',
    destructiveForeground: '#FFFFFF',
    border: '#D8D8F0',
    input: '#EEEEFF',
    online: '#22C55E',
    sent: '#7B5FFA',
    received: '#EEEEFF',
  },
  dark: {
    text: '#E8E8FF',
    tint: '#9B7FFF',
    background: '#0B0B14',
    foreground: '#E8E8FF',
    card: '#14141F',
    cardForeground: '#E8E8FF',
    primary: '#7B5FFA',
    primaryForeground: '#FFFFFF',
    secondary: '#1E1E2E',
    secondaryForeground: '#B0B0D8',
    muted: '#181828',
    mutedForeground: '#7878A8',
    accent: '#00C8FF',
    accentForeground: '#000000',
    destructive: '#FF3B5C',
    destructiveForeground: '#FFFFFF',
    border: '#252540',
    input: '#1A1A2A',
    online: '#4ADE80',
    sent: '#5B43D0',
    received: '#1E1E30',
  },
  radius: 14,
};

export default colors;
