kind = "mobile"
previewPath = "/"
title = "Nexus Messaging"
version = "1.0.0"
id = "artifacts/nexus-app"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 22626

[services.development]
run = "pnpm --filter @workspace/nexus-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexus-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nexus-app", "run", "serve" ]

[services.env]
PORT = "22626"
BASE_PATH = "/"
